/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * User.java
 *
 * Created on Apr 4, 2009, 10:51:16 PM
 */
package view;

import ImagePanel.ImagePanel;
import Utilities.Base64Image;
import controler.User_control;
import entity.User_entity;
import java.awt.BorderLayout;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.User_model;

/**
 *
 * @author Navneet
 */
public class User extends javax.swing.JFrame {

    User_entity _u = new User_entity();
    User_control _c = new User_control();
    ClassLoader cl = this.getClass().getClassLoader();
    java.awt.Toolkit toolkit = java.awt.Toolkit.getDefaultToolkit();
    private String SPath = "./data/";
    private ImagePanel _image;
    private boolean isImage;
Base64Image base64=new Base64Image();
    /** Creates new form User */
    public User() {

        initComponents();



    }
boolean status=false;
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pop = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jBAdd = new javax.swing.JButton();
        jCName = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jBRemove = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPass1 = new javax.swing.JPasswordField();
        jPass2 = new javax.swing.JPasswordField();
        jImagePanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Rname = new javax.swing.JTextField();
        jB_insert = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_add = new javax.swing.JMenuItem();
        jMenuItem_remove = new javax.swing.JMenuItem();
        jMenuItem_update = new javax.swing.JMenuItem();
        jMenuItem_retrive = new javax.swing.JMenuItem();

        pop.setForeground(new java.awt.Color(0, 0, 204));
        pop.setAutoscrolls(true);
        pop.setDoubleBuffered(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("User Administration");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setIconImage(toolkit.getImage(cl.getResource("image/java.png")));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("User"));
        jPanel1.setComponentPopupMenu(pop);

        jLabel1.setText("User Name:");

        jLabel2.setText("Password:");

        jBAdd.setText("Add");
        jBAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddActionPerformed(evt);
            }
        });

        jCName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCNameActionPerformed(evt);
            }
        });

        jLabel3.setText("User:");

        jBRemove.setText("Remove");
        jBRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRemoveActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("To Remove User:");

        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("To Add User:");

        jLabel6.setText("Confirm Password:");

        javax.swing.GroupLayout jImagePanelLayout = new javax.swing.GroupLayout(jImagePanel);
        jImagePanel.setLayout(jImagePanelLayout);
        jImagePanelLayout.setHorizontalGroup(
            jImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 133, Short.MAX_VALUE)
        );
        jImagePanelLayout.setVerticalGroup(
            jImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 133, Short.MAX_VALUE)
        );

        jLabel7.setText("Real Name:");

        jB_insert.setText("Insert");
        jB_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_insertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3)
                                .addGap(56, 56, 56)
                                .addComponent(jCName, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Rname, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPass1)
                                        .addComponent(jTName, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                        .addComponent(jPass2)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB_insert))
                            .addComponent(jBRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(Rname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jPass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jImagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAdd)
                    .addComponent(jB_insert))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jBRemove))
                .addContainerGap())
        );

        jMenu1.setText("File");

        jMenuItem_add.setText("ADD");
        jMenuItem_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_addActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_add);

        jMenuItem_remove.setText("Remove");
        jMenuItem_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_removeActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_remove);

        jMenuItem_update.setText("UpDate");
        jMenuItem_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_updateActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_update);

        jMenuItem_retrive.setText("Retrive");
        jMenuItem_retrive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_retriveActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_retrive);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRemoveActionPerformed
      remove();
}//GEN-LAST:event_jBRemoveActionPerformed

    private void jBAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddActionPerformed

adduser();
}//GEN-LAST:event_jBAddActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        loadCombo();
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem_retriveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_retriveActionPerformed
        JOptionPane.showMessageDialog(null, "not yet impleated", "Message", JOptionPane.ERROR_MESSAGE);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_retriveActionPerformed

    private void jMenuItem_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_updateActionPerformed
        remove();
        System.out.print(status);
if(status)
{
    adduser();
    System.out.print(status);
    status=false;
}
      //  JOptionPane.showMessageDialog(null, "not yet impleated", "Message", JOptionPane.ERROR_MESSAGE);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_updateActionPerformed

    private void jMenuItem_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_removeActionPerformed

         remove();
        //        JOptionPane.showMessageDialog(null, "not yet impleated", "Message", JOptionPane.ERROR_MESSAGE);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_removeActionPerformed

    private void jMenuItem_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_addActionPerformed
adduser();
        //        JOptionPane.showMessageDialog(null, "not yet impleated", "Message", JOptionPane.ERROR_MESSAGE);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_addActionPerformed

    private void jB_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_insertActionPerformed
        try {
            jImagePanel.removeAll();
            jImagePanel.repaint();
            // jImagePanel.add(lb7);
            //create frame
            JFrame f = new JFrame();
            f.setIconImage(toolkit.getImage(cl.getResource("image/java.png")));
            f.setTitle("select Image");
            //ask for image file
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(f);

            if (chooser.getSelectedFile().getPath() != null) {
                System.out.println("Path: " + chooser.getSelectedFile().getPath());

                //create panel with selected file
                _image = new ImagePanel(chooser.getSelectedFile().getPath(), jImagePanel.getWidth(), jImagePanel.getHeight());

                _image.setSize(jImagePanel.getSize());
                jImagePanel.add(_image, BorderLayout.CENTER);

                jImagePanel.repaint();

                isImage = true;
                //         lb7.setVisible(!isImage);
            }

        } catch (Exception e) {
            jImagePanel.removeAll();
            jImagePanel.repaint();
            //   jImagePanel.add(lb7);
            //  lb7.setVisible(true);

            System.out.println("Please verify that you selected a valid image file");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_insertActionPerformed

    private void jCNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCNameActionPerformed


        // TODO add your handling code here:
    }//GEN-LAST:event_jCNameActionPerformed

    /**
     * 
     */
    public void loadCombo() {
        jCName.removeAllItems();

        javax.swing.DefaultComboBoxModel dcm = null;
        dcm = (javax.swing.DefaultComboBoxModel) jCName.getModel();

        int size = User_model.AllUserKeys.size();

        // String[] names=null;

        for (int i = 0; i < size; i++) {
            dcm.addElement(User_model.AllUserKeys.get(i));
            //   names[i]=User_model.AllUserKeys.get(i);
        }

        //jCName.setModel(new javax.swing.DefaultComboBoxModel(names));

    }
void adduser()
    {

        String pass1 = String.valueOf(jPass1.getPassword());
        String pass2 = String.valueOf(jPass2.getPassword());

        if (jTName.getText().isEmpty() || pass1.isEmpty() || pass2.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please Enter all information", "Message",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            //comparing passwords
            if (String.valueOf(jPass1.getPassword()).compareTo(String.valueOf(jPass2.getPassword())) == 0) {
                _u.setName(jTName.getText());
                _u.setPassword(String.valueOf(jPass1.getPassword()));
                _u.setrName(Rname.getText());
    if(isImage==true)
                 {
                     _u.setPhoto(base64.codeBase64(_image.getImage()));
                 }
                 else
                 {
                    try {
                        _u.setPhoto(base64.codeBase64(ImageIO.read(new File("./temp/snap.jpg"))));
                    } catch (IOException ex) {
                        Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
                    }


                 }
                if (_c.Add(_u, SPath)) {
                    javax.swing.JOptionPane.showMessageDialog(null, "User has been successfully registered",
                            "Confirmation Message", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    loadCombo();
                /*    jTName.setText("");
                    jPass1.setText("");
                    jPass2.setText("");
                    Rname.setText("");
                     jImagePanel.removeAll();
                          jImagePanel.repaint();
                 *
                */}
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Please comfirm passwords!!", "Message",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
        }

}

void remove()
    {
      if (jCName.getSelectedItem() == null) {
            javax.swing.JOptionPane.showMessageDialog(null, "there is nothing to remove.", "Message", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        //    return false;
        }
      else
      {

            boolean ex = false;
            String user = null;
            try {
                user = (String) jCName.getSelectedItem();
            } catch (Exception e) {
                ex = true;
            }

            if (ex == false) {
                boolean f = false;


                User_model.loadAllEntries(SPath);

                for (User_entity _user : User_model.AllUsers) {
                    if (user.compareTo(_user.getName()) == 0) {
                        f = true;
                        _u = _user;
                        break;
                    }
                }

                if (f == true) {
                    if (_c.delete(_u, SPath)) {
                        loadCombo();
                        javax.swing.JOptionPane.showMessageDialog(null, "User has been successfully removed", "Confirmation Message",
                                                     javax.swing.JOptionPane.INFORMATION_MESSAGE);
                        status =true;
                        System.out.println("delete"+status);
                     //   return true;
                    }
                }



            } else {

                javax.swing.JOptionPane.showMessageDialog(null, "Please select all user...", "Message",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
                        status =true;
                        System.out.println("delete"+status);
              //  return false;
            }
        }

}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new User().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Rname;
    private javax.swing.JButton jBAdd;
    private javax.swing.JButton jBRemove;
    private javax.swing.JButton jB_insert;
    private javax.swing.JComboBox jCName;
    private javax.swing.JPanel jImagePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_add;
    private javax.swing.JMenuItem jMenuItem_remove;
    private javax.swing.JMenuItem jMenuItem_retrive;
    private javax.swing.JMenuItem jMenuItem_update;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPass1;
    private javax.swing.JPasswordField jPass2;
    private javax.swing.JTextField jTName;
    private javax.swing.JPopupMenu pop;
    // End of variables declaration//GEN-END:variables
}
